version: '3'
services:
  op:
     build: ./
     volumes:
     - "./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf"
     - "./lua_code/:/opt/lua/"
     - "./luarocks:/opt/luarocks"
     ports:
     - "80:80"